
[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "ffmpeg"]

[variables]
PYTHONUNBUFFERED = "1"

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate && pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "gunicorn -w 1 -k gthread --threads 2 --timeout 300 -b 0.0.0.0:$PORT app:app"
