[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "ffmpeg"]

[variables]
PYTHONUNBUFFERED = "1"

[phases.install]
cmds = ["python -m venv /opt/venv && . /opt/venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --timeout 900 --workers 1 --threads 2"
